/*******************************************************************
  Copyright (C) 2001-2018 Analog Devices, Inc. All Rights Reserved
*******************************************************************/

/* Generated by tcl */

#ifndef __VDK_ASM_OFFSETS_H_
#define __VDK_ASM_OFFSETS_H_


#define VDK_MUTEX_SIZE (20U)
#define VDK_MUTEX_LEN (5U)
#define __VDK_SIZEOF_IDElement_ (4)
// BEGIN_INTERNALS_STRIP
#define OFFSET_IDTable_m_TableSize_ (4)
#define OFFSET_IDTable_m_IDTable_ (0)
#define OFFSET_IDTableElement_m_ObjectPtr_ (0)
#define OFFSET_IDTableElement_m_IndexCount_ (4)
#define OFFSET_Semaphore_m_Value_ (52)
#define OFFSET_Semaphore_m_ID_ (0)
#define OFFSET_Semaphore_m_PendingThreads_ (32)
#define OFFSET_Semaphore_m_PendingThreads_pHead_ (32)
#define OFFSET_Semaphore_m_MaxCount_ (48)
#define OFFSET_Semaphore_m_Period_ (44)
#define __VDK_SIZEOF_Semaphore_ (56)
#define ENUM_kThreadError_ (1)
#define ENUM_kISRError_ (3)
#define ENUM_kUnknownSemaphore_ (-2147483644)
#define ENUM_kUnknownEventBit_ (-2147483643)
#define ENUM_kBadIOID_ (-2147483631)
#define ENUM_kAbort_ (-2147483596)
#define ENUM_kThreadStackOverflow_ (-2147483593)
#define ENUM_kStackCheckFailure_ (6)

#define OFFSET_Thread_m_DebugInfoP_ (52)

#define OFFSET_DebugInfo_m_nNumTimesRun_ (0)
#define OFFSET_DebugInfo_m_llRunStartCycles_ (12)
#define OFFSET_DebugInfo_m_llRunLastCycles_ (20)
#define OFFSET_DebugInfo_m_llRunTotalCycles_ (28)
#define OFFSET_DebugInfo_m_tRunStartTime_ (40)
#define OFFSET_DebugInfo_m_tRunLastTime_ (44)
#define OFFSET_DebugInfo_m_tRunTotalTime_ (48)

#define __VDK_SIZEOF_HistoryEvent_ (16)
#define __VDK_SIZEOF_HistoryStruct_ (16)
#define ENUM_VDK_kSemaphorePosted_ (-2147483646)
#define ENUM_VDK_kEventBitSet_ (-2147483644)
#define ENUM_VDK_kEventBitCleared_ (-2147483643)
#define ENUM_VDK_kDeviceActivated_ (-2147483639)
#define ENUM_VDK_kThreadStatusChange_ (-2147483637)
#define ENUM_VDK_kThreadSwitched_ (-2147483636)

#define __VDK_SIZEOF_EventBit_ (4)

#define POINTER_CONVERSION_Semaphore_TO_TMK_DpcElement_ (20)
#define POINTER_CONVERSION_DeviceDriver_TO_TMK_DpcElement_ (8)
#define POINTER_CONVERSION_Thread_TO_TMK_Thread_ (4)

// END_INTERNALS_STRIP

#endif /* __VDK_ASM_OFFSETS_H_*/

